version: '3'
services:
  app:
    image: node:14-stretch-slim
    container_name: container1
    #network_mode: "host"
    ports:
      - 8080:8080
    restart: always
    working_dir: /home/app
    tty: true
    user: "${UID}:${GID}"
    volumes:
      - /etc/passwd:/etc/passwd:ro #ホスト側のpasswd, groupファイルをNode.jsコンテナに読取専用でマウント。これで内外のユーザで作成したファイルに対してのアクセスでPermisson deniedが出ないようにしている
      - /etc/group:/etc/group:ro
      - ./user:/home/${APP_USER}
      - ./src:/home/app
      - ./data:/home/data
    command: bash
    #command: node index.js
    networks:
      - app-network #Node.jsからMongoDBにアクセスできるように、専用の仮想ネットワークapp-networkでつながるようにしている
    depends_on:
      - mongo
  mongo:
    image: mongo:4.2.5-bionic
    container_name: container2
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    #ports:
    #  - 27099:27017
    volumes:
      - ./data/db:/data/db
    command:
      - mongod
    networks:
      - app-network #Node.jsからMongoDBにアクセスできるように、専用の仮想ネットワークapp-networkでつながるようにしている
networks:
  app-network:
    external: true